// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuddyPawsApi.Models;

namespace MuddyPawsApi.Migrations
{
    [DbContext(typeof(MuddyPawsDBContext))]
    [Migration("20200318224803_updatedPetModel")]
    partial class updatedPetModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MuddyPawsApi.Models.MuddyPawsPets", b =>
                {
                    b.Property<int>("PetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CheckinDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckoutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PetName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PetOwnersAddress")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PetOwnersEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PetOwnersName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PetOwnersNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PetSize")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PetType")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpecialNeeds")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("PetID");

                    b.ToTable("muddyPawsPet");
                });
#pragma warning restore 612, 618
        }
    }
}
